apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-config
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_SSLMODE: {{ .Values.config.dbSslmode | quote }}
  ADDR: {{ .Values.config.addr | quote }}
