// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (phone, telegram_chat_id)
VALUES ($1, $2)
RETURNING id, phone, telegram_chat_id, password_hash, totp_secret, totp_enabled, status, created_at, updated_at, pin_hash
`

type CreateAccountParams struct {
	Phone          string
	TelegramChatID int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Phone, arg.TelegramChatID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.TelegramChatID,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinHash,
	)
	return i, err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE accounts SET totp_enabled = TRUE, status = 'active', updated_at = now() WHERE id = $1
`

func (q *Queries) EnableTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableTOTP, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, phone, telegram_chat_id, password_hash, totp_secret, totp_enabled, status, created_at, updated_at, pin_hash FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.TelegramChatID,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinHash,
	)
	return i, err
}

const getAccountByPhone = `-- name: GetAccountByPhone :one
SELECT id, phone, telegram_chat_id, password_hash, totp_secret, totp_enabled, status, created_at, updated_at, pin_hash FROM accounts WHERE phone = $1
`

func (q *Queries) GetAccountByPhone(ctx context.Context, phone string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPhone, phone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.TelegramChatID,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinHash,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE accounts SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updatePinHash = `-- name: UpdatePinHash :exec
UPDATE accounts SET pin_hash = $2, updated_at = now() WHERE id = $1
`

type UpdatePinHashParams struct {
	ID      uuid.UUID
	PinHash pgtype.Text
}

func (q *Queries) UpdatePinHash(ctx context.Context, arg UpdatePinHashParams) error {
	_, err := q.db.Exec(ctx, updatePinHash, arg.ID, arg.PinHash)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE accounts SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateStatusParams struct {
	ID     uuid.UUID
	Status AccountStatus
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.Exec(ctx, updateStatus, arg.ID, arg.Status)
	return err
}

const updateTOTPSecret = `-- name: UpdateTOTPSecret :exec
UPDATE accounts SET totp_secret = $2, updated_at = now() WHERE id = $1
`

type UpdateTOTPSecretParams struct {
	ID         uuid.UUID
	TotpSecret pgtype.Text
}

func (q *Queries) UpdateTOTPSecret(ctx context.Context, arg UpdateTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, updateTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}
