// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatus string

const (
	AccountStatusPendingVerification AccountStatus = "pending_verification"
	AccountStatusPendingSetup        AccountStatus = "pending_setup"
	AccountStatusActive              AccountStatus = "active"
	AccountStatusBlocked             AccountStatus = "blocked"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus
	Valid         bool // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type Account struct {
	ID             uuid.UUID
	Phone          string
	TelegramChatID int64
	PasswordHash   pgtype.Text
	TotpSecret     pgtype.Text
	TotpEnabled    bool
	Status         AccountStatus
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PinHash        pgtype.Text
}

type VerificationCode struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Code        string
	Attempts    int32
	MaxAttempts int32
	ExpiresAt   pgtype.Timestamptz
	UsedAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
