// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_codes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (account_id, code, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, code, attempts, max_attempts, expires_at, used_at, created_at
`

type CreateVerificationCodeParams struct {
	AccountID uuid.UUID
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode, arg.AccountID, arg.Code, arg.ExpiresAt)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Code,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveCodeByAccountID = `-- name: GetActiveCodeByAccountID :one
SELECT id, account_id, code, attempts, max_attempts, expires_at, used_at, created_at FROM verification_codes
WHERE account_id = $1
  AND used_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCodeByAccountID(ctx context.Context, accountID uuid.UUID) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getActiveCodeByAccountID, accountID)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Code,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markCodeUsed = `-- name: MarkCodeUsed :exec
UPDATE verification_codes SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCodeUsed, id)
	return err
}
